check invalid vmstat line
./hw_vars: line 61: =: command not found

Signed-off-by: Fengguang Wu <fengguang.wu@intel.com>

diff --git a/hw_vars b/hw_vars
--- a/hw_vars
+++ b/hw_vars
@@ -58,6 +58,10 @@ nr_cpu=$(grep -c processor /proc/cpuinfo)
 nr_node=$(echo /sys/devices/system/node/node* | wc -w)
 
 while read key val; do
+	[[ $key && $val =~ [0-9]+ ]] || {
+		echo "invalid vmstat line: $key $val"
+		break
+	}
 	eval $key=$val
 done < /proc/vmstat
 
