hw_vars: fix $val quotation
./hw_vars: line 104: [: too many arguments

Signed-off-by: Fengguang Wu <fengguang.wu@intel.com>

diff --git a/hw_vars b/hw_vars
--- a/hw_vars
+++ b/hw_vars
@@ -101,11 +101,12 @@ nr_cpu=$(grep -c processor /proc/cpuinfo)
 nr_node=$(echo /sys/devices/system/node/node* | wc -w)
 
 while read key val; do
-	[ -n "$key" -a -n ${val} -a "${val##*[0-9]}" = '' -a "${val%%[0-9]*}" = '' ] || {
-		echo "invalid vmstat line: $key $val"
+	[ -n "${val}" ] || continue
+	[ -z "${val##*[0-9]}" -a -z "${val%%[0-9]*}" ] || {
+		echo "invalid vmstat line: $key $val" >&2
 		break
 	}
-	eval $key=$val
+	eval "$key=$val"
 done < /proc/vmstat
 
 reclaimable=$((nr_free_pages + nr_file_pages))
